apiVersion: v1
kind: Service
metadata: 
  name: auth-svc
  labels:
    svc: auth
spec:
  selector: 
    app: auth-svc 
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc 
  labels: 
    app: auth-svc 
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: auth-svc 
  template: 
    metadata:
      labels: 
        app: auth-svc 
    spec:
      containers:
        - name: auth-svc 
          image: auth:v1 
          ports: 
            - containerPort: 80