apiVersion: v1
kind: Service
metadata:
  name: demo-main
spec:
  type: NodePort
  selector:
    app: demo-frontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  labels:
    app: demo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels: 
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: frontend:v1 
          ports:
            - containerPort: 80``